### PR TITLE
Correct typos and improve syntax for clarity

### PR DESCRIPTION
**Pull request by DanielKehoe**
I hope the improvements are useful.

### CODE REVIEW

**Comment by PragTob** [comment]
Hi there!

Thank you so much for contributing! :heart: 
Thanks especially for the hard work on the grammar etc. - I know it's not a fun task :-)

One question/discussion though:
You replaced the double quoted strings with the single quoted ones. I thought about that too and it is also how I use to write ruby code (only use double quotes when needed). However, especially in the beginning I try to "hide" as many variations, corner cases and little distinctions from learners as I found that it mostly confuses them. Plus double quotes are a bit more natural/often sued in daily life (at least in Germany).

Would like to hear your thoughts about this :-)

Otherwise totally awesome and ripe for merging + a big thanks!
Tobi

**Comment by DanielKehoe** [comment]
Hi Tobi,

Great concept and excellent execution! I hope my edits didn't step on your writing style too much :-)

I agree with you about limiting variations for beginners. Certainly you could drop the single vs. double quotes detail. However I found in teaching at RailsBridge that it was helpful to introduce single vs. double quotes to newcomers as they will encounter both frequently and they ask what is the difference. Also newcomers will encounter interpolation frequently and without an introduction #{} is a squiggly mystery.

I've added a footer to force a little extra space at the bottom of the checklist, with a credit to you (!). Of course you could change the footer links.

I also added two links to "More Resources" which you may decide to remove as they link to resources I've created. One is an in-depth primer "What is Ruby on Rails" which is basic reading for beginners. The other link is to a list of all the Rails tutorials I know about, with recommendations based on skill level and learning style. I agree with you that Hartl's book is excellent but I've found that it's not suitable for everyone (and a bit unfair to all the other authors of tutorials that his work is often the only one mentioned).

-- Daniel

**Comment by PragTob** [comment]
Totally agree about interpolation, wanted to keep it away from them in the first run but you are totally right that it is just too common. I just don't like that it is yet another thing with curly braces (tm). But necessary so thanks for the addition :-)

You're right on "" vs. '' so maybe I will add a bit more text about this but as they are both common it is good.

I like the idea of showing off more resources straight on the page and not through my blog. I'll create an issue for that it can/should be it's own site just like about. I think a list of curated resources right in place will really help people.

Will take a look at your resources. A bit busy right now, just back home from Railsberry :-) So making those additions might take me some time.

Thank you so much for your contributions. I love open source!

Tobi

**Comment by PragTob** [comment]
:+1:

**Comment by DanielKehoe** [comment]
I'll tweet the cheatsheet URL to 10.3K @rails_apps followers today.

> a list of curated resources

I've been working on http://railsapps.github.io/ruby-and-rails.html

Let's find a way to make a curated list open and crowdsourced. Maybe a RGSoC project?

-- Daniel

**Comment by PragTob** [comment]
Wow thanks, well i wanted to wait to go real public but well then this might as good of a place as any to do so :-)

A curated open and crowd sourced list sounds like a _really_ good idea for Rails Girls Summer of Code. We might take this to the mailing list or private mail :-)

**Comment by DanielKehoe** [comment]
daniel@danielkehoe.com

**Comment by DanielKehoe** [comment]
I've started development on the app here:
https://github.com/RailsApps/ruby-on-rails-directory

With a task list and user stories here:
https://trello.com/board/ruby-on-rails-directory/517c9cb060f673c01e000dc9

**Pull request merged**
