### PR TITLE
unix filenames

### PR DESCRIPTION
**Pull request by bkleinen**
Hi Tobi, 

this is a great cheat cheat and I will give it to my students! Reading it I noticed 2 little things that I'd like to improve, hence the pull request.
About the license, for content type stuff like this I usually use a Creative Commons License like this one:
http://creativecommons.org/licenses/by-nc-sa/3.0/de/

Cheers

Béla

### CODE REVIEW

**Comment by bkleinen** [comment]
- maybe the note about filenames is better placed somewhere else.

**Comment by jrgifford** [comment]
Do keep in mind that the NC part means it can't be used as part of a commercially available course, tutorial, etc.

**Comment by bkleinen** [comment]
good point, then maybe another creative commons licence without the nc - 
http://creativecommons.org/choose/

**Comment by PragTob** [comment]
Hi Béla, thanks for the contributions and happy to see that you will use it in your course ;-)

See you at RUG-B this Thursday?!

Tobi

**Pull request merged**
