### PR TITLE
typo in about.html

### PR DESCRIPTION
**Pull request by abelards**
Hi Tobi and all, I want to translate this Cheat Sheet in French in the next few weeks, thanks for the work!
In the meantime, here's a tiny typo fix.
:heart:

### CODE REVIEW

**Comment by PragTob** [comment]
Ahh thanks a lot!

about translations, don't have a really god solution for that (yet) - suggestions welcome!

**Comment by abelards** [comment]
About translations, well, it's mostly static (perfect, simplicity trumps everything) so the question is: how will we duplicate the content? I can:
- do a FR branch
- do a FR repo
- do a FR.html

**Comment by PragTob** [comment]
Well a branch wouldn't because github pages afaik only supports the gh-pages branch. A separate repo would be okay-ish but I think my favorite would be an fr subfolder and that we could have a dropdown linking to it.

Just worried about update problems e.g. when the main one gets updated with new content, how do we notify translators? :-)

edit: 
Oh there does not seem to be a good recognized way to do this yet: [a little tweet](https://twitter.com/parkr/status/376171523158990848)

**Comment by abelards** [comment]
OK for subfolders, I'll do that in my version, let me at least a week (it'll be a busy one at work).
About notifications, I'd say do that as a GitHub issue so those concerned are warned.
That's more or less how they do in https://github.com/ruby/www.ruby-lang.org

**Comment by PragTob** [comment]
@abelards thanks! But take your time, no rush or anything - work at your pace. It's great either way and I know that it's a lot of work. Also feel free to submit PRs with typos/better explanations that you find on the way :-)

**Pull request merged**
