### PR TITLE
FR translation: WIP

### PR DESCRIPTION
**Pull request by abelards**
Hi Tobi,
I've translated about.html and the header/footer of the others.
I'm going to translate the rest before the end of the week.

I just wanted to check: is this how you envisioned the translations,
with a directory and 3 HTML pages translated?
See you,

### CODE REVIEW

**Comment by PragTob** [comment]
Yeah this seems good to me, however unfortunately the layouting/templating is still missing :-( #21

**Comment by abelards** [comment]
Of course, I didn't check the CSS links >.<
Sorry about that, at least I know it's the right direction, I'll add the rest soon(ish)!
Thanks for pointing that, sorry for not checking.

**Comment by abelards** [comment]
Hi Tobi, I've added some fixes (layouts/templating), pages and some more text.
Does that look better? Sorry, I planned on moving faster but got a huge project at work.
See you,

**Comment by PragTob** [comment]
No problem @abelards ! Thanks a lot!

I'm at a conf right now but will take a look at it in the coming days!

**Comment by PragTob** [comment]
Looks great to me! Sorry that it took me rather long to get back.

It's cool for me to try and read the french translations (had french in school). 

So do you want to merge it now and have the translation as a work in progress or you want to wait?

Only thing missing is a link to the translation from the main page but I can put that in :-)

Thanks!!! :+1:

**Comment by abelards** [comment]
Well let the PR there for people to see and participate,
I've finished some rushes so I'll be resuming work soon.

A bit sad I couldn't do it for RailsGirls Paris but we had 1 coach for 2 trainees so it was like private mentoring, so this kind of resources was less needed ^^

**Comment by PragTob** [comment]
Oh you did Rails Girls Paris? Cool!

So I guess you met @berlintam - she was a student of mine.. or well is. But I feel she's way beyond the "student" level - as she coached in Rails Girls Paris and so much other cool stuff =)

Cheers,
Tobi

**Comment by abelards** [comment]
I did met her, she was a coach and RailsGirls Paris was awesome :)
I hope to contribute more to the guide in the next week.

**Pull request merged**
