### PR TITLE
Dropdown menu for #ruby

### PR DESCRIPTION
**Pull request by blairanderson**
I added a bootstrap dropdown menu for the ruby sub-categories. this fixes issue #10

The bootstrap dropdown normally requires a click but i added 2 lines of CSS which activate in upon hover. 

The dropdown is a little finicky and i'm not sure why, i didn't add anything tricky so i'm not sure why its happening like that.

### CODE REVIEW

**Comment by PragTob** [comment]
Thank you very much for your contribution!

This looks pretty cool, however you are right it acts quite a bit finicky... for me it basically only works when going straight down from the caret. I'd love to merge this, but therefore the behaviour should be better. I don't have time right now and also not over the weekend :(

It would be splendid if you or someone else came up with a way to fix this!

**Comment by blairanderson** [comment]
I could not come up with a way to fix it.

On Fri, Apr 26, 2013 at 5:24 PM, Tobias Pfeiffer
notifications@github.comwrote:

> Thank you very much for your contribution!
> 
> This looks pretty cool, however you are right it acts quite a bit
> finicky... for me it basically only works when going straight down from the
> caret. I'd love to merge this, but therefore the behaviour should be
> better. I don't have time right now and also not over the weekend :(
> 
> It would be splendid if you or someone else came up with a way to fix this!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PragTob/rails-beginner-cheatsheet/pull/20#issuecomment-17105373
> .

## 

Blair Anderson
425-829-1130

**Comment by PragTob** [comment]
:-( sad but thanks for trying!!! :-D

Maybe I will get to it, or someone else picks this up. Would appreciate it!

**Comment by PragTob** [comment]
Thanks, @blairand - got around to playing with it. Turns out a mere `top: 95%` in the css was enough to fix this!

So thanks to you we know have a dropdown menu!! =) :heart:

**Comment by blairanderson** [comment]
Very cool. I have started to play around with Jekyll so that we can dry up
the views into a layout folder.

On Sat, May 18, 2013 at 6:24 AM, Tobias Pfeiffer
notifications@github.comwrote:

> Thanks, @blairand https://github.com/blairand - got around to playing
> with it. Turns out a mere top: 95% in the css was enough to fix this!
> 
> So thanks to you we know have a dropdown menu!! =) [image: :heart:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PragTob/rails-beginner-cheatsheet/pull/20#issuecomment-18100116
> .

## 

Blair Anderson
425-829-1130

**Comment by PragTob** [comment]
:-) that sounds splendid! I should take a closer look at jekyll myself or well just ask @parkr and offer a couple of beers in return! =)

**Comment by parkr** [comment]
I :heart: jekyll and am always happy to answer questions! I hang around in the #jekyll irc channel a bunch too so just hop in and leave a message and i'll respond when i log in next :)

**Pull request merged**
